
/*******************************************************************************
* generated by lcd-image-converter rev.90f620c from 2017-10-04 21:09:44 +0500
* image
* filename: unsaved
* name: no_wifi_small
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/

#ifndef _NO_WIFI_SMALL_H_
#define _NO_WIFI_SMALL_H_

#include <stdint.h>


static const uint8_t image_data_no_wifi_small[96] = {
    // ∙∙∙███∙∙∙∙∙∙∙████∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙████∙██████████████∙∙∙∙∙∙∙∙
    // ∙∙∙█████████████████████∙∙∙∙∙∙
    // ∙∙∙∙██████████████████████∙∙∙∙
    // ∙∙██████████████████████████∙∙
    // ∙██████████∙∙∙∙∙∙∙∙██████████∙
    // ████████████∙∙∙∙∙∙∙∙∙∙████████
    // ██████∙∙████████████∙∙∙∙██████
    // █████∙∙████████████████∙∙█████
    // ████∙∙██████████████████∙∙████
    // ∙∙∙∙∙████████████████████∙∙∙∙∙
    // ∙∙∙∙██████████████████████∙∙∙∙
    // ∙∙∙∙██████∙∙∙█████∙∙██████∙∙∙∙
    // ∙∙∙∙█████∙∙████████∙∙█████∙∙∙∙
    // ∙∙∙∙███∙∙███████████∙∙∙███∙∙∙∙
    // ∙∙∙∙∙∙∙∙█████████████∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙██████████████∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙██████∙∙███████∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙████∙∙∙∙∙∙∙████∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙██∙∙∙∙█∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙████∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙██████∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙██████∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙████∙∙∙∙∙∙∙∙∙∙∙∙∙
    0x1c, 0x07, 0x80, 0x00, 
    0x1e, 0xff, 0xfc, 0x00, 
    0x1f, 0xff, 0xff, 0x00, 
    0x0f, 0xff, 0xff, 0xc0, 
    0x3f, 0xff, 0xff, 0xf0, 
    0x7f, 0xe0, 0x1f, 0xf8, 
    0xff, 0xf0, 0x03, 0xfc, 
    0xfc, 0xff, 0xf0, 0xfc, 
    0xf9, 0xff, 0xfe, 0x7c, 
    0xf3, 0xff, 0xff, 0x3c, 
    0x07, 0xff, 0xff, 0x80, 
    0x0f, 0xff, 0xff, 0xc0, 
    0x0f, 0xc7, 0xcf, 0xc0, 
    0x0f, 0x9f, 0xe7, 0xc0, 
    0x0e, 0x7f, 0xf1, 0xc0, 
    0x00, 0xff, 0xf8, 0x00, 
    0x00, 0xff, 0xfc, 0x00, 
    0x00, 0xfc, 0xfe, 0x00, 
    0x00, 0xf0, 0x1e, 0x00, 
    0x00, 0x03, 0x08, 0x00, 
    0x00, 0x07, 0x80, 0x00, 
    0x00, 0x0f, 0xc0, 0x00, 
    0x00, 0x0f, 0xc0, 0x00, 
    0x00, 0x07, 0x80, 0x00
};

#endif
